-----------------------------------------------------------
-- Medical Items
-----------------------------------------------------------

Items = {}

Items.Medical = {
    bandage = {
        label = 'Bandage',
        description = 'Basic wound dressing to stop minor bleeding',
        weight = 100,
        stackable = true,
        max_stack = 20,
        usable = true,
        heal_amount = 5,
        bleed_reduce = 1,
        use_time = 3000,
        animation = 'bandage',
        ems_only = false,
    },
    medkit = {
        label = 'Medical Kit',
        description = 'Advanced medical kit for treating moderate injuries',
        weight = 500,
        stackable = true,
        max_stack = 5,
        usable = true,
        heal_amount = 25,
        bleed_reduce = 2,
        use_time = 8000,
        animation = 'medkit',
        ems_only = false,
    },
    firstaid = {
        label = 'First Aid Kit',
        description = 'Basic first aid supplies for emergency treatment',
        weight = 300,
        stackable = true,
        max_stack = 10,
        usable = true,
        heal_amount = 15,
        bleed_reduce = 1,
        use_time = 5000,
        animation = 'firstaid',
        ems_only = false,
    },
    defibrillator = {
        label = 'Defibrillator',
        description = 'Emergency cardiac defibrillation device',
        weight = 2000,
        stackable = false,
        max_stack = 1,
        usable = true,
        use_time = 8000,
        animation = 'defib',
        ems_only = true,
        min_rank = 2,
    },
    ecg_machine = {
        label = 'ECG Machine',
        description = 'Portable electrocardiogram monitor',
        weight = 3000,
        stackable = false,
        max_stack = 1,
        usable = true,
        use_time = 5000,
        animation = 'ecg',
        ems_only = true,
        min_rank = 1,
    },
    oxygen_tank = {
        label = 'Oxygen Tank',
        description = 'Portable oxygen supply for breathing support',
        weight = 4000,
        stackable = false,
        max_stack = 1,
        usable = true,
        use_time = 5000,
        animation = 'oxygen',
        ems_only = true,
        min_rank = 0,
    },
    stretcher = {
        label = 'Stretcher',
        description = 'Patient transport stretcher',
        weight = 5000,
        stackable = false,
        max_stack = 1,
        usable = true,
        use_time = 3000,
        animation = 'stretcher',
        ems_only = true,
        min_rank = 0,
    },
    wheelchair = {
        label = 'Wheelchair',
        description = 'Patient mobility wheelchair',
        weight = 4000,
        stackable = false,
        max_stack = 1,
        usable = true,
        use_time = 3000,
        animation = 'wheelchair',
        ems_only = false,
        min_rank = 0,
    },
    crutches = {
        label = 'Crutches',
        description = 'Walking support for leg injuries',
        weight = 1500,
        stackable = false,
        max_stack = 1,
        usable = true,
        use_time = 2000,
        animation = 'crutch',
        ems_only = false,
    },
    medical_bag = {
        label = 'Medical Bag',
        description = 'Complete EMS field medical bag',
        weight = 3000,
        stackable = false,
        max_stack = 1,
        usable = true,
        use_time = 3000,
        animation = 'medbag',
        ems_only = true,
        min_rank = 1,
    },
    bodybag = {
        label = 'Body Bag',
        description = 'Deceased patient transport bag',
        weight = 2000,
        stackable = true,
        max_stack = 5,
        usable = true,
        use_time = 5000,
        animation = 'bodybag',
        ems_only = true,
        min_rank = 0,
    },
    painkillers = {
        label = 'Painkillers',
        description = 'Over-the-counter pain relief medication',
        weight = 50,
        stackable = true,
        max_stack = 30,
        usable = true,
        pain_reduce = 20,
        use_time = 2000,
        animation = 'pill',
        ems_only = false,
    },
    morphine = {
        label = 'Morphine',
        description = 'Strong prescription painkiller',
        weight = 50,
        stackable = true,
        max_stack = 10,
        usable = true,
        pain_reduce = 50,
        use_time = 3000,
        animation = 'inject',
        ems_only = true,
        min_rank = 2,
    },
    antibiotics = {
        label = 'Antibiotics',
        description = 'Prevents and treats infection',
        weight = 50,
        stackable = true,
        max_stack = 20,
        usable = true,
        use_time = 2000,
        animation = 'pill',
        ems_only = false,
    },
    adrenaline = {
        label = 'Adrenaline Shot',
        description = 'Emergency epinephrine injection',
        weight = 100,
        stackable = true,
        max_stack = 5,
        usable = true,
        use_time = 3000,
        animation = 'inject',
        ems_only = true,
        min_rank = 2,
    },
    blood_bag = {
        label = 'Blood Bag',
        description = 'Blood transfusion unit',
        weight = 500,
        stackable = true,
        max_stack = 5,
        usable = true,
        blood_restore = 30,
        use_time = 10000,
        animation = 'iv',
        ems_only = true,
        min_rank = 3,
    },
    saline = {
        label = 'Saline IV',
        description = 'Intravenous saline solution',
        weight = 400,
        stackable = true,
        max_stack = 10,
        usable = true,
        blood_restore = 15,
        use_time = 8000,
        animation = 'iv',
        ems_only = true,
        min_rank = 1,
    },
    splint = {
        label = 'Splint',
        description = 'Bone immobilization splint',
        weight = 200,
        stackable = true,
        max_stack = 10,
        usable = true,
        use_time = 6000,
        animation = 'splint',
        ems_only = false,
    },
    surgical_kit = {
        label = 'Surgical Kit',
        description = 'Complete surgical instrument set',
        weight = 2000,
        stackable = false,
        max_stack = 1,
        usable = true,
        use_time = 15000,
        animation = 'surgery',
        ems_only = true,
        min_rank = 3,
    },
}

-----------------------------------------------------------
-- Ox Inventory Item Definitions (for ox_inventory/data/items.lua)
-----------------------------------------------------------
Items.OxDefinitions = {
    { name = 'bandage', label = 'Bandage', weight = 100, stack = true, close = true, description = 'Basic wound dressing' },
    { name = 'medkit', label = 'Medical Kit', weight = 500, stack = true, close = true, description = 'Advanced medical kit' },
    { name = 'firstaid', label = 'First Aid Kit', weight = 300, stack = true, close = true, description = 'Basic first aid supplies' },
    { name = 'defibrillator', label = 'Defibrillator', weight = 2000, stack = false, close = true, description = 'Cardiac defibrillation device' },
    { name = 'ecg_machine', label = 'ECG Machine', weight = 3000, stack = false, close = true, description = 'Portable ECG monitor' },
    { name = 'oxygen_tank', label = 'Oxygen Tank', weight = 4000, stack = false, close = true, description = 'Portable oxygen supply' },
    { name = 'stretcher', label = 'Stretcher', weight = 5000, stack = false, close = true, description = 'Patient transport stretcher' },
    { name = 'wheelchair', label = 'Wheelchair', weight = 4000, stack = false, close = true, description = 'Patient wheelchair' },
    { name = 'crutches', label = 'Crutches', weight = 1500, stack = false, close = true, description = 'Walking support' },
    { name = 'medical_bag', label = 'Medical Bag', weight = 3000, stack = false, close = true, description = 'EMS field medical bag' },
    { name = 'bodybag', label = 'Body Bag', weight = 2000, stack = true, close = true, description = 'Deceased transport bag' },
    { name = 'painkillers', label = 'Painkillers', weight = 50, stack = true, close = true, description = 'Pain relief medication' },
    { name = 'morphine', label = 'Morphine', weight = 50, stack = true, close = true, description = 'Strong painkiller' },
    { name = 'antibiotics', label = 'Antibiotics', weight = 50, stack = true, close = true, description = 'Anti-infection medication' },
    { name = 'adrenaline', label = 'Adrenaline Shot', weight = 100, stack = true, close = true, description = 'Emergency epinephrine' },
    { name = 'blood_bag', label = 'Blood Bag', weight = 500, stack = true, close = true, description = 'Blood transfusion unit' },
    { name = 'saline', label = 'Saline IV', weight = 400, stack = true, close = true, description = 'IV saline solution' },
    { name = 'splint', label = 'Splint', weight = 200, stack = true, close = true, description = 'Bone immobilization splint' },
    { name = 'surgical_kit', label = 'Surgical Kit', weight = 2000, stack = false, close = true, description = 'Surgical instruments' },
}
